---
- name: import global variables
  include_vars:
    dir: "{{ inventory_dir }}/group_vars/"

- name: remove unused packages
  package:
    state: absent
    name:
      - hexchat
      - pidgin
      - thunderbird
      - xfburn

- name: add target user
  user:
    name: "{{ target_user }}"
    comment: "{{ target_user_name }}"
    groups: wheel
    append: yes
    generate_ssh_key: yes
