---
- name: Check if installed
  stat:
    path: "{{ user_home_dir }}/.okteto"
  register: okteto_dir

- name: ensure okteto directory exists
  become_user: "{{ target_user }}"
  file:
    path: "{{ user_home_dir }}/.okteto"
    state: directory
  when: okteto_dir.stat.exists == false

- name: Get okteto binary
  become_user: "{{ target_user }}"
  get_url:
    url: "https://downloads.okteto.com/cli/okteto-linux-amd64"
    dest: "{{ user_home_dir }}/.okteto/okteto"
  when: okteto_dir.stat.exists == false

- name: Set Permissions
  file:
    path: "{{ user_home_dir }}/.okteto/okteto"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    # when specifying mode using octal numbers, add a leading 0
    mode: 0700

- name: Add okteto to $PATH.
  copy:
    dest: /etc/profile.d/okteto.sh
    content: 'PATH="{{ user_home_dir }}/.okteto:$PATH"'