---
- name: import third-party repository signing keys
  rpm_key: key={{ item }} state=present
  loop:
    - https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: install selinux
  package:
    state: present
    name:
      - libselinux-python

- name: add/upgrade RPM repositories
  package:
    state: latest
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm
      - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm

- name: add other third-party repositories
  get_url:
    dest: "/etc/yum.repos.d/"
    url: "{{ item }}"
    setype: system_conf_t
    seuser: system_u
  loop:
    - https://negativo17.org/repos/fedora-spotify.repo

- name: install base packages
  ### Package notes ###
  # Fedora packaging tools: fedora-packager, fedpkg, copr-cli
  # chromaprint-tools: Capture digital fingerprints of audio files
  # gstreamer1-plugins-bad-nonfree: MPEG2 codec support
  # jpegoptim: Utility to optimize JPEG files
  # meld: Visual diff and merge tool
  # network-manager-applet: Network control / status applet for NetworkManager
  # poppler-utils: Command line utilities for converting PDF files
  package:
    state: present
    name:
      - ansible
      - bash-completion
      - buildah
      - docker
      - docker-compose
      - fedpkg
      - fedora-packager
      - ffmpeg
      - firewalld
      - git
      - golang
      - google-roboto-slab-fonts
      - gstreamer-ffmpeg
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-nonfree
      - gstreamer1-plugins-ugly
      - htop
      - jpegoptim
      - jq
      - libvirt
      - libvirt-devel
      - meld
      - network-manager-applet
      - podman
      - powerline-fonts
      - pulseaudio-utils
      - spotify-client
      - telegram-desktop
      - '@virtualization'
      - google-chrome-stable