---
- name: import third-party repository signing keys
  rpm_key: key={{ item }} state=present
  loop:
    - https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: install selinux
  package:
    state: present
    name:
      - libselinux-python

- name: add/upgrade RPM repositories
  package:
    state: latest
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm


- name: add custom repos
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
  with_items:
    - kubernetes.repo
    - gcloud.repo

- name: add other third-party repositories
  get_url:
    dest: "/etc/yum.repos.d/"
    url: "{{ item }}"
    setype: system_conf_t
    seuser: system_u
  loop:
    - https://negativo17.org/repos/fedora-spotify.repo

- name: upgrade all packages
  package:
    name: "*"
    state: latest
        
- name: install base packages
  ### Package notes ###
  # Fedora packaging tools: fedora-packager, fedpkg, copr-cli
  # chromaprint-tools: Capture digital fingerprints of audio files
  # gstreamer1-plugins-bad-nonfree: MPEG2 codec support
  # jpegoptim: Utility to optimize JPEG files
  # meld: Visual diff and merge tool
  # network-manager-applet: Network control / status applet for NetworkManager
  # poppler-utils: Command line utilities for converting PDF files
  package:
    state: present
    name:
      - ansible
      - awscli
      - bash-completion
      - buildah
      - docker
      - docker-compose
      - fedpkg
      - fedora-packager
      - ffmpeg
      - firewalld
      - fzf
      - git
      - golang
      - google-roboto-slab-fonts
      - google-chrome-stable
      - google-cloud-sdk
      - guake
      - gstreamer-ffmpeg
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-nonfree
      - gstreamer1-plugins-ugly
      - htop
      - jpegoptim
      - jq
      - kubectl
      - libvirt
      - libvirt-devel
      - libappindicator
      - meld
      - network-manager-applet
      - podman
      - powerline-fonts
      - pulseaudio-utils
      - spotify-client
      - telegram-desktop
      - '@virtualization'