---
- name: set up Justin's preferred Fedora Workstation configuration
  hosts: workstation
  become: yes

  roles:
    - system/base
    - system/fedora-workstation
    - apps/base-workstation
    - apps/bash
    - apps/git
    - apps/powerline-go
    - apps/fzf
    - apps/ssh
    - apps/vim
    - apps/bench
    - apps/krew
    - role: gantsign.visual-studio-code
      users:
        - username: pau
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - wholroyd.jinja
            - ms-python.python
          visual_studio_code_settings: {
            "editor.rulers": [80, 100, 120],
            "editor.renderWhitespace": true,
            "files.associations": {
              "Vagrantfile": "ruby"
            }
          }